server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true #将IP注册到Eureka Server上，如果不配置就是机器的主机名。
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    fetch-registry: false # 是否检索服务。该应用为服务注册中心，职责为注册和发现服务，无需检索服务，设置为 false
    register-with-eureka: false    #单节点情况下关闭服务互相注册
